# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1428, 865)
        MainWindow.setMaximumSize(QtCore.QSize(1428, 865))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 450, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 450, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.CamFrontIn = QtWidgets.QLabel(self.centralwidget)
        self.CamFrontIn.setGeometry(QtCore.QRect(50, 70, 491, 301))
        self.CamFrontIn.setFrameShape(QtWidgets.QFrame.Box)
        self.CamFrontIn.setLineWidth(2)
        self.CamFrontIn.setText("")
        self.CamFrontIn.setObjectName("CamFrontIn")
        self.CamFrontOut = QtWidgets.QLabel(self.centralwidget)
        self.CamFrontOut.setGeometry(QtCore.QRect(720, 70, 491, 301))
        self.CamFrontOut.setFrameShape(QtWidgets.QFrame.Box)
        self.CamFrontOut.setLineWidth(2)
        self.CamFrontOut.setText("")
        self.CamFrontOut.setObjectName("CamFrontOut")
        self.CamBackIn = QtWidgets.QLabel(self.centralwidget)
        self.CamBackIn.setGeometry(QtCore.QRect(50, 480, 491, 301))
        self.CamBackIn.setFrameShape(QtWidgets.QFrame.Box)
        self.CamBackIn.setLineWidth(2)
        self.CamBackIn.setText("")
        self.CamBackIn.setObjectName("CamBackIn")
        self.CamBackOut = QtWidgets.QLabel(self.centralwidget)
        self.CamBackOut.setGeometry(QtCore.QRect(720, 480, 491, 301))
        self.CamBackOut.setFrameShape(QtWidgets.QFrame.Box)
        self.CamBackOut.setLineWidth(2)
        self.CamBackOut.setText("")
        self.CamBackOut.setObjectName("CamBackOut")
        self.btnTable = QtWidgets.QPushButton(self.centralwidget)
        self.btnTable.setGeometry(QtCore.QRect(1240, 10, 121, 31))
        self.btnTable.setObjectName("btnTable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APS"))
        self.label.setText(_translate("MainWindow", "Car Front In"))
        self.label_2.setText(_translate("MainWindow", "Car Front Out"))
        self.label_3.setText(_translate("MainWindow", "Car Back In"))
        self.label_4.setText(_translate("MainWindow", "Car Back Out"))
        self.btnTable.setText(_translate("MainWindow", "Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
